### ISSUE TITLE
Signals not being emitted

### ISSUE THREAD

**Issue by Acid3croco** [edx/django-user-tasks#94]
* django-user-tasks version: 1.3.0
* Django version: 3.1.2
* Python version: 3.8.1
* Operating System: macOS 11

### Description

I was trying to connect signals to the one i guess were emited when a task was created or succeeded. So I added a function in signals and tried to work out signals in django by also putting login signal to ensure signals were working.
Despite the task being conducted and finished (successfully i guess since it does what i want it to do) i have no signal emitted in any case.

I tried multiples ways and endded up adding django-debug-toolbar  3.1.1
Using this package i saw an error message in the logs
<img width="1543" alt="Screenshot 2020-11-16 at 15 30 35" src="https://user-images.githubusercontent.com/24960450/99264402-b3784400-2820-11eb-91fd-ee31a39d44e2.png">

So I looked into the ```create_user_task()``` method inside ```user_tasks/signals.py``` in the package
It looks like there is conflicts between body argument where args and kwars should be, but they seems to be in the ```header``` argument passed in ```**kwarg``` of ```create_user_task()``` under the name ```"argsrepr"``` and ```"kwargsrepr"``` (i dont know much about these names tho)

Am i doing something wrong? 
Thank you,
Yoann

### What I Did

my tasks.py file inside my app
```
class ImportTask(UserTask):
    @classmethod
    def generate_name(cls, arguments_dict):
        serie = Serie.objects.get(pk=arguments_dict['serie_id'])
        return 'Import of {}'.format(serie)

    @staticmethod
    def calculate_total_steps(arguments_dict):
        return 100


@shared_task(base=ImportTask, bind=True)
def import_csv(self, user_id, notification_key, path_file, serie_id, **kwargs):
    uploadCandles(path_file, serie_id)
```

my signals.py file with logged_in and out working as espected but nothing happening for the others
```
def user_logged_in_handler(sender, request, user, **kwargs):
    print('OUI')


def user_logged_out_handler(sender, request, user, **kwargs):
    print('NON')


def user_task_stopped_handler(**kwargs):
    print('User task stoped')


@receiver(task_success)
def task_success_handler(result, **kwargs):
    print('User task succeed')


@task_success.connect
def task_succeeded_handler(sender=None, **kwargs):
    print(sender)
    if isinstance(sender, UserTaskMixin):
        print('User task succeed')


user_logged_in.connect(user_logged_in_handler)
user_logged_out.connect(user_logged_out_handler)
user_task_stopped.connect(user_task_stopped_handler)
```

**Comment by Acid3croco** [comment]
Ok after digging more I restarded everything including celery and as far as i know signals are know working, so i just hadnt restarded celery properly i guess... Sorry for the inconvenience.

The log error is still here tho, but yea some signals are working as expected for ```user_task_stop```.

That being said, should i use the signals in the file signals or pass by the ```user_task_stop``` or use celery signals ?

**Comment by etiennelatulippe** [comment]
@Acid3croco I got the same problem. Do you know what was the issue and how to resolve that?
